### ISSUE TITLE
Usage with gulp

### ISSUE THREAD

**Issue by whitneyit** [galenframework/galen#212]
I put together an example [repo](https://github.com/whitneyit/galen-test) of how to use galen with [gulp](http://gulpjs.com/) via a [`gulpfile.js`](https://github.com/whitneyit/galen-test/blob/master/gulpfile.js) and I just thought that I'd share :smile:

**Comment by whitneyit** [comment]
I was wondering if you wanted to add this to the docs section perhaps? I can submit a PR for that if need be?

**Comment by ishubin** [comment]
Hey, thanks a lot! Article describing this would be great!
You can write your article and send a pull request to this repo https://github.com/galenframework/galenframework.com (this repo contains all the sources of galenframework.com)

At the moment all articles are authorless since all of them were written by me. But we can also add a "written by ..." section below each article

Let me know if you need any help with it. The website is powered by [Blogix](http://blogix.info/) with custom extended markdown. All of the documentation articles are located in this folder https://github.com/galenframework/galenframework.com/tree/master/db/docs

**Comment by whitneyit** [comment]
Sounds good mate. I'll send the pull request to that repo. Thank you for the consideration to put a written by section in the tutorial, it's awesome how the open source community pulls together like that :smile:

I was thinking of using a blockquote at the top of the article similar to the way Chris Coyier does over at http://css-tricks.com. An example of this can be found in the following article: http://css-tricks.com/gooey-effect.

I'll close this issue and continue the conversation on the upcoming PR
