### ISSUE TITLE
Error rate as range instead of int

### ISSUE THREAD

**Issue by phystem** [galenframework/galen#243]
Right now for SpecAligned and SpecCentered the error rate is given as single value(in px)
I've gone through the code and you have declared <b>errorRate as int in SpecObjectWithErrorRate</b>
Is it possible to change it to a <b>Range</b> so that we can do the following

menu-item-1
    aligned horizontally: menu-item-2 <b>1 to 2 px</b>

label
    centered horizontally inside: box <b>~10px</b>

**Comment by ishubin** [comment]
I doubt that it will be changed like that since we have to keep the backwards compatibility. Also could you please explain what is the exact reason for you to look for such a change?

The trick with specs ```aligned``` and ```centered``` is that they calculate the absolute offset from the line. If you introduce a spec like ```aligned horizontally: menu-item-2 5 to 7 px``` that would mean that it expects the offset always from 5 to 7 pixels. So it will fail if there is no offset and both elements are aligned. To me that doesn't make any sense. At least I haven't seen an example where it would be logical to check like that. Also keep in mind that it calculates absolute offset. So the object could be above and below the alignment line. So this means that at some point you won't care if the object is misaligned by 6px to the top or by 6 px to the bottom (in case of horizontal alignment).

**Comment by ishubin** [comment]
Also normally it is a good idea not to use error values bigger than 3 pixels. The max I use is 1 px error range. And also in rare cases.

**Comment by hypery2k** [comment]
From my experience it depends on what type of layout you use in your CSS/HTML 

In my project we have columns which are sometimes 1/3 width. So in many case there are rounding issues. So for us 2px tolerance across all major browsers lead to stable tests. Another result is that we we're now using more alignment between elements which is suitable for us

**Comment by ishubin** [comment]
@hypery2k I agree with you. What I meant is that I am always trying to use the lowest value possible so that I can catch new layout issues. But what I still don't understand is why would anyone use a range of error rate in the "aligned" spec. Just an int value is enough for this.

**Comment by hypery2k** [comment]
I agree, i personally just see a syntax issue as some people except a range here, too ;)
