### ISSUE TITLE
TestReport should store debugging information as map of key values

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#250]
It would be helpfull to add extend the TestReportNode with a field url to  show up the loaded page URL:
![selection_003](https://cloud.githubusercontent.com/assets/979121/6915850/05dea5fc-d798-11e4-95bb-13500168d44b.png)

@ishubin Let me know if it's ok for you to add this feature.
I will the add it to TestReportNode, to the API and to the report.

As an alternative we could add a key-value map to the the TestReportNode, so then everybody can put additional information he likes there. It should support HTML, so no escape would be nice.

**Comment by ishubin** [comment]
@hypery2k I am not sure about this. Because click function not always lead to page url change. In case of DHTML application it wouldn't be that useful. On the other hand, it might be useful to track the state of application in the reports after each action (current url, cookies, page source). I would say this is a bigger story then just having url. Personally I am against the url solution, but would prefer something that is more flexible and customizable. So I think your idea with additional information is great, lets just think on all the details and only then start implementing it. 
Anyway since Galen became a complete functional framework I think it is best to provide the tools for the user to do it themselves in their framework configuration. For instance in JavaScript tests users would change the prototype functions for GalenPages.PageElement object. In Java tests - they would just do that on the TestReportNode as you proposed.
Also I would prefer to hide this data in the report and only show it when users clicks some button (like on the menu). 
So again I really like your idea but it should be carefully thought through. What do you think?

**Comment by hypery2k** [comment]
I'm totally with you. I've also like the more flexible. I would thing just of a simple map with key --> value, e.g.

```
url => 'Loaded page: <a href="http://mydomain/myTestPage">myTestPage</a>',
usedGrid => 'GridNode: 172.11.212.1',
notes => 'Some test notes'
```
The screenshot is misleading. I just wanted a way to add dynamic information below a spec check, maybe about the environment, used grid node, browser ....

**Comment by ishubin** [comment]
Ok, I guess we are on the same page here. The only thing I would like to mention is that we shouldn't provide all that debug data by default. Basically end-users should manage all of that themselves. All what we need to do - is to store the map data in the node as your proposed and then render it in html report

**Comment by hypery2k** [comment]
sounds great

**Comment by ishubin** [comment]
I have implemented this feature in the release-2.1 branch.
Here is how it will look like. There will be an "extras" link on the node:
![screenshot - 29082015 - 16 48 16](https://cloud.githubusercontent.com/assets/949577/9562505/25536d1c-4e6e-11e5-87f5-6fe41da0f165.png)

And when you click it it will give you this popup:

![screenshot - 29082015 - 16 48 56](https://cloud.githubusercontent.com/assets/949577/9562508/2c1b978c-4e6e-11e5-8a2f-7463f88159bb.png)

**Comment by ishubin** [comment]
@hypery2k what do you think about it?

**Comment by hypery2k** [comment]
i like it. Really cool
