### ISSUE TITLE
getting error: Cannot find locator for "menu-item-1" in page spec

### ISSUE THREAD

**Issue by kchuykov** [galenframework/galen#255]
Galen 1.6.1. 

It sometimes gives me this error even though I have the locator  menu-item-*   

 I think this happens after I user 'run' to run a javascript file in the test suit. 

When this happens, it seem to  also skip checks that look like this:
menu-item-1
    absent

here is a sample project with the report:
https://dl.dropboxusercontent.com/u/110244097/galen-accelerator-locators-issues.zip

**Comment by ishubin** [comment]
Could you please try adding a wait between "run" and "check" actions? For now the only thing I can think of is that it has to do with the DHTML. If I open your page I see that it takes a second for a menu to be rendered. What happens in your case is this:
1. When dealing with multi objects (the ones that have '*' in name) Galen fetches them via given locator right away before even parsing the rest of the spec and before applying actual validation.
2. The menu at that moment is still not rendered so it means that Galen can't fetch any objects. So it doesn't create those menu items at all.
3. When it comes to actual validation Galen takes a screenshot. On that screenshot you can see the rendered menu item because on that moment it was enough time for the menu to be rendered.

That is my theory. You can actually wait for a specific element on the page like here http://galenframework.com/docs/reference-galen-test-suite-syntax/#Conditionbasedtimeout

Let me know if that helps you in this case

**Comment by kchuykov** [comment]
ok Thanks, waits  seem to work. closing for now.
