### ISSUE TITLE
Css property for color needs to be handled

### ISSUE THREAD

**Issue by phystem** [galenframework/galen#257]
search
    css background-color is: #e24648

"search" css property "background-color" is "rgba(226, 70, 72, 1)" but should be "#e24648"

selenium is returning color values as rgba values 
are you gonna handle that or we have to give input as selenium format only
like   css background-color is: rgba(226, 70, 72, 1)

**Comment by ishubin** [comment]
To be honest I don't really know what to do with this spec. I was really against it as it breaks the main idea of Galen Framework - test the UI but not the code. But I had to introduce it since a lot of users wanted to test the font size and family properties. I guess we should leave it as it is at the moment. Because testing css property values doesn't really mean you are testing what it will look at the end. These kind of things should be rather tested with ```color scheme``` or ```image``` specs

**Comment by phystem** [comment]
ya we can test it with color scheme but for that we have to specify range in %
is it possible to give something like
  color scheme: black 
instead of
   color scheme: >90% black 
so that we can check the color

**Comment by ishubin** [comment]
Well, it was intentional. It makes it more clear how much of the given color you expect on the image. But I will think about it. In your example it is not really clear what Galen should expect and it which conditions it should fail. What if it has found only 5% of black color?

**Comment by phystem** [comment]
if they dint give the range, then the default range should be >90% or 95-100%. that's what i meant

**Comment by ishubin** [comment]
You can do that via custom rules:

```
@@ rule: dominant color is %{color}
   color scheme: >90% ${color}
@@ end

login-button
    | dominant color is black
```

**Comment by ishubin** [comment]
Here you can read more about it http://galenframework.com/docs/reference-galen-spec-language-guide/#CustomRules
