### ISSUE TITLE
Relative width as pecentage instead of px

### ISSUE THREAD

**Issue by phystem** [galenframework/galen#259]
Right now if we check width or height with other element[screen,viewport,webelement] we give the range as percentage.
But in report it is showing as pixel.It should show as percentage as it will be useful to modify the specs

Suggested Report 
Is it possible to display them as green or blue
![galen](https://cloud.githubusercontent.com/assets/11405204/7063036/bbf34b98-dec0-11e4-9752-10b7564025d5.PNG)

**Comment by ishubin** [comment]
I've been thinking about this for quite some time. I agree that it should verify in percentages instead of converting that to float values. I don't think we need multiple error messages for this case. Just instead of float values we will display percentage.

**Comment by phystem** [comment]
Not multiple messages .either the percentage [second] or both percentage+px[third one]

**Comment by ishubin** [comment]
Ah, ok. I got it now :)

**Comment by hypery2k** [comment]
i would like to have both in combination, so something like this 
![untitled 2](https://cloud.githubusercontent.com/assets/979121/7072900/fcca96ba-deef-11e4-9311-1800fe6da3fc.png)

**Comment by ishubin** [comment]
I have fixed the decimal formatting in the error message and updated all the tests. At the moment all the tests are green. Thank you @phystem for the idea and code. It is very useful.
I am not closing the issue because I want to change the way the percentage ranges are used in validations. I am working on it.

**Comment by ishubin** [comment]
I have added rounding of pixels and added a test that checks the situation when the percentage is calculated as 33.333333% and it is verified against 33.3%
Still I am not sure about this implementation. I will try to change the verification of percentage based ranges in actual percentages and not absolute pixels value (I think as it is now it might lead to false negatives).
Also I am not sure at what precision should we verify the percentage. At the moment it has precision of one (10.5%, 33.3% etc.) I definitely don't want to increase precision as I think it doesn't really make a lot of sense but at the same time not sure if the value after point should be taken into account or not

**Comment by phystem** [comment]
I'm also not sure about the precision..I think precision of two would be fine..Also if you are giving, then the value after point should be taken into account.

**Comment by ishubin** [comment]
I think it is a good idea. Will try to add precision check for all values

**Comment by ishubin** [comment]
Finally I have finished this refactoring. Its quite a big one. I should have thought this through initially :)

From now on Galen will not take the digits after point in  all values unless user defines it. 
So if you choose a spec ```width: 24% of header/width``` and the actual percentage appears as 24.5, then galen would ignore the .5 and will not fail. But if you would write ```width: 24.4% of header/width```, galen will fail as it will compare two values 24.4 and 24.5 with a precision of one digit after point.
For all this to work I had to change the way Range object is used and instead of Double type I have introduced RangeValue type. RangeValue object takes care of precision parsing, printing and comparison.

Please let me know if it all not working. I have fixed all unit tests but haven't yet had the time to check it manually in my galen project

**Comment by phystem** [comment]
I've checked it and it seems the spec generated by pagedump is deviating by one/two units.

![image](https://cloud.githubusercontent.com/assets/11405204/7142879/42842e52-e2f9-11e4-8c3b-e6ffae861c21.png)

**Comment by ishubin** [comment]
You have tested this with the latest commits on release-2.0 branch?

I see an issue in the last check. It says "height is 540% [346px] instead of 541% [346px]". As I can see something is wrong in the calculation. Could you please provide me the areas of "Welcome" and "MeNotes-MenuItem" objects from that report? I will then be able to debug the calculations and will try to find out where it rounds the value incorrectly.

**Comment by phystem** [comment]
Ya I've tested with latest commits only..
"MyNotes-MenuItem":{"area":[151,70,108,64]
"Welcome":{"area":[67,154,860,346]

**Comment by ishubin** [comment]
Thanks! Will check the calculations and investigate this issue
