### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by yurist38** [galenframework/galen#503]
Hi, guys! We are planning to start using Galen in our project. Right now I'm playing with it and I must say that great job was done! Thank you all for that!
So I'm just wondering do you have any plans to add ES6 syntax support? That would be really nice to have...

**Comment by hypery2k** [comment]
What ES6 features you need? Currently we don't have a plan for ES6 yet.

**Comment by yurist38** [comment]
Import/export, arrow functions, and others. But anyway thanks for quick reply!

**Comment by ishubin** [comment]
@yurist38 No, we don't plan to introduce ES6 into Galen Framework due to the fact that underneath it uses an embedded Java lib for JavaScript execution (Mozilla Rhino). Though there are plans to extend galen so that it runs as a service with exposed RESTful APIs. That way it will be possible to call its functions from any other language (node, ruby, python etc).  Though that would still require quite some work.
