### ISSUE TITLE
Enable retry failed test in Galen Test Suite Syntax

### ISSUE THREAD

**Issue by mpluta-airhelp** [galenframework/galen#588]
Can we have similar functionality to https://github.com/galenframework/galen/issues/184 in http://galenframework.com/docs/reference-galen-test-suite-syntax/. That would be awesome!

**Comment by ishubin** [comment]
Hi, I have decided not to extend Galen Test Suite syntax anymore so that I can focus on Galen core. But if I remember correctly you can mix test suite files with js and have the retry logic in js. Galen should pick this up, convert all the test suite files into tests, pick up the retry handler in js and apply the retry mechanism.

**Comment by mpluta-airhelp** [comment]
Thanks @ishubin will try that approach!
