### ISSUE TITLE
Add COUNT spec for multiple objects

### ISSUE THREAD

**Issue by claytonneal** [galenframework/galen#89]
When using multiple object identification, would be great to have a COUNT spec
Example:

```
=====================================
menu-items-*      css         .menuitem
=====================================

menu-items-*
  count: 5
```

**Comment by ishubin** [comment]
Implemented count spec in release-2.1 branch. It can work as a normal spec under any object. Basically it doesn't care under which object it was defined. So ideally you could try to use it by defining under "global" object so that it reads better.

```
global:
    count any menu-item-* is 0
```

Also it is possible to count only visible or absent items. Not sure if we need to count absent items but counting visible items is definitely useful.
Also it supports multiple objects expressions as well as complete range support
```
global:
    count visible "menu-item-*, coment-*" is 6 to 8
```
