### ISSUE TITLE
Incorrect imported spec file path resolution  

### ISSUE THREAD

**Issue by shabalin** [galenframework/galen#95]
If you put main and imported spec into the classpath root, e.g.

classes/
    main.spec 
    fragment.spec

`main.spec`

```
@@ import fragment.spec
....
```

When we run the test we pass `/main.spec` value as a spec file and following error is occurred:

```
net.mindengine.galen.parser.FileSyntaxException: java.io.FileNotFoundException: Can't find file or resource: //fragment.spec
    in /main.spec:1
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:96)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:68)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:59)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:111)
```

obviously the resource `//fragment.spec` could not be found, it needs to be '/fragment.spec'

to work this around we have put spec files under subdirectory of classpath

classes/
    specs/
        main.spec 
        fragment.spec

and call the test passing `/specs/main.spec`

so the issue is not critical but produce some inconvenience

**Comment by thaddeusdiamond-smartercloud** [comment]
This is now reproducible in Galen 2.3.4.  The culprit is line 56 of ImportProcessor.java, when pageSpecHandler.getContextPath() is equal to "/".  Perhaps there's a way to turn this into null when it's at the root (there are a few other locations where "/" is concated to the context path, like SpecImageProcessor too).
